config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'blog/:id', to: 'blog#show', as: 'post'
  get 'blog', to: 'blog#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @title = 'Danger 2.0 Blog'
    @posts = Dir.entries('./app/views/posts').
      select { |f| f.ends_with?('.html.erb') }.
      map { |f|
        id = f.chomp('.html.erb')
        { id: id, title: remove_order(id) }
      }.reverse
  end

  def show
    @title = "Danger 2.0 | #{remove_order(params[:id])}"

    render "posts/#{params[:id]}"
  end

  private

  def remove_order(slug)
    slug[3..-1].titleize
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = 'Amy Hogue | Portfolio'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <title><%= @title || 'Amy Hogue' %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/posts/01-welcome.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="banner welcome-post-banner" style="background-image: url(<%= image_path('http://res.cloudinary.com/ahg1/image/upload/v1536893063/feature_ex044p.jpg')%>);">


    </div>
    <div class="banner-comment mr-15"><p>(Photo: Panajachel, Guatemala 2018)</p></div>
  </div>
</div>

<div class="container post-container">
  <div class="row">
    <div class="banner-heading">
      <h1>Danger 2.0</h1>
    </div>

    <p>Ahhhh...So much to catch you up on.</p>

    <p>
      I used to have a blog called <a href="https://dangervdanger.wordpress.com/" target="_blank" rel="noopener">Danger v. Danger</a> (Danger is an old nickname with not that funny of a story behind it), so this blog Danger 2.0 is (hopefully) a more mature version.
    </p>
    <p>
      You probably know some of my story, but I promise you don't know all of it. I'll give you a quick recap of the past year and maybe fill in the details later.
    </p>
    <p>
      About a year ago I left my job in Social Work to go Rio De Janeiro, Brazil and (start to learn) to code (Ruby, but you don't care).  I thought after Rio I'd end up in Peru. I don't particularly love Peru, but I thought I'd move there for a certain doctor I met in the States. Shit didn't work out with Doctor (does it ever?) and I went home, but by that time I had my mind set on traveling because Denver is going through it's rebellious teenage years right now and I don't have room for that.
    </p>

    <p>Here's a summary of Brazil in 3 pictures: </p>
  </div>
</div>

<div class="container-fluid">
  <div class="row photo-row">

    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/c_scale,w_1666/v1536893068/rio4_bb88zm.jpg', class: "medium-photo"%>
    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/c_scale,w_851/v1536893056/rio2_lvwjui.jpg', class: "medium-photo"%>
    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/c_scale,w_954/v1536893057/rio3_dftx9b.jpg', class: "medium-photo"%>
  </div>
</div>

<div class="container post-container">
  <div class="row">
    <p>
      So now I'm in Mexico! ¡Olè!
    </p>
    <p>
      I went to Chiapas, Mexico for 6 weeks, Guatemala for 7 weeks and then to Mexico City for 3 months. I have been coding 5 days a week, doing yoga (basic, I know) and being a tourist on the weekends. I would guess that I lost 5 pounds, gained 7 pounds, lost 4 and might be right around there, in case you care (you probably don't, but I would be curious). Currently, I'm in Puebla Mexico and that's where this story kicks off. Oh, that and a need to avoid social media because:
    </p>
    <ol>

      <li> <p>Trump: I don't care anymore. Nothing is changing and no one is changing their minds. Call me when he's impeached.</p></li>
      <br>
      <li><p>FOMO or whatever it is where everyone looks happier than me.</p></li>
      <br>
      <li><p>POOR BOUNDARIES</p></li>
    </ol>

    <p>
      I won't be too vague here with number 3: one mother fucker showed up in tiny little Panajachel, Guatemala randomly and unannounced thinking it was romantic to track me down (thanks to social media) but it was actually SCARY AS HELL and another who refuses to take "no" and "fuck off" for an answer...and has for years. So...yep, you have to be on the short list to read this blog. Which means that you're important to me and I trust you not to chop me into cubes and store me in a shoebox <img draggable="false" class="emoji" alt="🙂" src="https://s0.wp.com/wp-content/mu-plugins/wpcom-smileys/twemoji/2/svg/1f642.svg" scale="0"> <img draggable="false" class="emoji" alt="🙂" src="https://s0.wp.com/wp-content/mu-plugins/wpcom-smileys/twemoji/2/svg/1f642.svg" scale="0"> <img draggable="false" class="emoji" alt="🙂" src="https://s0.wp.com/wp-content/mu-plugins/wpcom-smileys/twemoji/2/svg/1f642.svg" scale="0">
    </p>

    <p>
      I'm hoping this is a bit interactive. I want to know about you and yours as much as share about me and...me. I'm going to push myself to be honest which I don't do that much. I'm kind of a liar sometimes. Or at least, SUPER private but since I'm far away from home I have a need to connect...with people who won't scalp me and make me into a fresh hair doll <img draggable="false" class="emoji" alt="🙂" src="https://s0.wp.com/wp-content/mu-plugins/wpcom-smileys/twemoji/2/svg/1f642.svg" scale="0"> <img draggable="false" class="emoji" alt="🙂" src="https://s0.wp.com/wp-content/mu-plugins/wpcom-smileys/twemoji/2/svg/1f642.svg" scale="0"> <img draggable="false" class="emoji" alt="🙂" src="https://s0.wp.com/wp-content/mu-plugins/wpcom-smileys/twemoji/2/svg/1f642.svg" scale="0">
    </p>

    <p><strong>***Side note: I'm joking about the murder stuff, obviously , but "no means no" is really important and not having that respected was actually scary and so...please believe females when they say "no" or express that something feels unsafe. I've found that the more confident I am, the more men seem to want a piece of my power and occasionally, they succeed.</strong></p>

    <p>
      Here's a summary of my time in Guatemala in 4 photos:
    </p>

  </div>
</div>
<div class="container-fluid">
  <div class="row photo-row">
    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/c_scale,w_635/v1536893055/guat1_yvr9gj.jpg', class: "medium-photo"%>
    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/c_scale,w_647/v1536893055/guat2_z4jgsv.jpg', class: "medium-photo"%>
    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/c_scale,w_583/v1536893058/guat3_lrw9lo.jpg', class: "medium-photo"%>
    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/c_scale,w_899/v1536893058/guat4_rsgwbf.jpg', class: "medium-photo"%>
  </div>
</div>
<div class="container">
  <div class="row nav-links">

    <%= link_to blog_path do %>
      <i class="fa fa-home nav-arrow" aria-hidden="true"></i>
      <h4>Home</h4>
    <% end %>

    <%= link_to post_path(id: '02-mexico') do %>
      <h4 class ="tr">Newer Post</h4>
      <i class="fa fa-arrow-right nav-arrow" aria-hidden="true"></i>
    <% end %>

  </div>
</div>

app/views/posts/02-mexico.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="banner welcome-post-banner" id = "mexico-featured-photo" style="background-image: url(<%= image_path('http://res.cloudinary.com/ahg1/image/upload/v1536893874/feature_bu5j7o.jpg')%>);">
  </div>
  <div class="banner-comment mr-15"><p>(Photo: Mexico City a.k.a. CDMX - 2018)</p></div>
   </div>
</div>

<div class="container post-container">
  <div class="row">
    <div class="banner-heading">
      <h1>Mexico y Yo</h1>
    </div>
   <p>
     Ever since I was really young I’ve always had Mexican friends and always loved the closeness and warmth of the culture. I can remember when I was about 4 or 5 a friend’s mom taught me the word “agua” in Spanish and I was AMAZED. Since my great Hellen Keller moment, I was kind of obsessed with Spanish. When I started learning Spanish in college, I dreamed of spending a <em>bunch</em> of time in Mexico and going deep into the culture as I learned more about the history and art of the country. I pictured myself wearing long, flowing, colorful skirts; grinding corn on my metete; hand making tortillas for random children and maybe even plowing a field with my buRRRRo (emphasis on rolling the rr to show that I can).
   </p>
    <p>
      When I was 18, I came to Mexico City for the first time. I only spoke enough Spanish to almost kill myself and my travel mates twice (once by ordering two <em>buckets</em> of beer instead of two<em> bottles</em> and the second by accidentally convincing a burly bouncer in a bar that they were both “basuras” or trash). It was my first time outside of the first world and it was pretty shocking and not what I imagined Mexico would be, but still amazing.
    </p>
    <p>
      After that, I spent about 7 years thinking, as most of us do, that Mexico is far too dangerous to visit, even though I still really wanted to go. I was sad, but thought it wasn’t worth the risk. That slowly started changing for me as I realized that parts of Mexico are unsafe just like parts of the US aren’t safe according to the news. Last year, I was talking to a Britt and a Brazilian and they were asking about gun sales in WalMart. It had never occurred to me that it sounds weird to everyone else that you can buy an assault weapon and pancakes in the same location. So yeah, we seem a little extreme to outsiders. I read a little more about the different states of Mexico and saw that, as is usually the case, Mexico isn’t what it seems in the news.
    </p>
  </div>
</div>

<div class="container-fluid">
  <div class="row photo-row">
    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/c_fill,h_875,w_832/v1536893874/puebla1_w9mefg.jpg', class: "uniform-photo"%>
    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/v1536893872/puebla4_c63tby.jpg', class: "uniform-photo"%>
  </div>
  <div class="row photo-row">
    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/c_scale,w_918/v1536893875/puebla5_qf4qci.jpg', class: "uniform-photo"%>
    <%= image_tag 'https://res.cloudinary.com/ahg1/image/upload/c_scale,w_1250/v1537313184/IMG_8145_sselo2.jpg', class: "uniform-photo"%>
  </div>
</div>

<div class="container post-container">
  <div class="row">
    <p>
      Have you seen the episode of Arrested Development where George Michael is in Mexico and he goes to Wetzles Pretzels every single day and that’s his entire Mexico experience? That hits close to home for my current Monday to Friday. I live in this very suburban-looking area, go to a fancy people gym and then come to Starbucks to code. I cook at home and make the exact same things I would eat in Colorado. Sometimes I chuckle to myself thinking about what people must imagine my life is like vs. what it is. This place (Puebla City) looks like Miami without the beaches and everyone thinks I’m weird and maybe poor because I walk everywhere instead of driving or being driven.
    </p>
    <p>
      To make up for my bland lifestyle and lack of buRRRos I try to experience the culture on the weekends. This last weekend was all about tacos al pastor. Do you know what tacos al pastor are? Is that common knowledge? I can’t tell anymore. If you don’t know: they actually have Lebanese roots. They are shawarma style meat, but with the twist of Mexican spices and pineapple and they cook on a gyro-looking “trompo.” You can tell how popular a taqueria is by the size of the trompo, stay away from small trompos. The theatrics of the taco are half of the fun because the dude that serves them cuts them with a giant machete-like knife and flips a little piece of the pineapple down at the end. It’s glorious and I enjoy watching taco making just as much as watching construction (which is a lot).
    </p>

    <p>
      This weekend I went to a Taco festival in a random little town here in the state of Puebla. The tacos were free, so there were a lot of people (over 400,000 tacos served). Actually I got some anxiety with the quantity of people, so I wasn’t up for going around to all the stands. I still got some amazing tacos in the town that’s said to be the birthplace of tacos al pastor and the lead singer of the band that was playing pointed me out as the only gringa in the giant sea of people. Also the tacos were really little and I like that. I like it when they make the tacos tiny so you can crush an ungodly number of tacos (like...ten to fifteen) and feel really powerful. I’m not trying to be dramatic, but tacos. are. life. Also Starbucks and Wetzles Pretzles. Viva Mexico.
    </p>

  </div>
</div>
<div class="container-fluid">
  <div class="row photo-row">
    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/v1536893870/tacos2_trrvil.jpg', class: "uniform-photo"%>
    <%= image_tag 'http://res.cloudinary.com/ahg1/image/upload/c_fill,e_auto_brightness,h_375,w_332/v1536893875/tacos3_jw0cti.jpg', class: "uniform-photo"%>
  </div>
</div>

<div class="container">
  <div class="row nav-links">

    <%= link_to post_path(id: '01-welcome') do %>
      <i class="fa fa-arrow-left nav-arrow" aria-hidden="true"></i>
      <h4>Older Post</h4>
    <% end %>

    <%= link_to blog_path do %>
      <i class="fa fa-home nav-arrow" aria-hidden="true"></i>
      <h4>Home</h4>
    <% end %>

    <%= link_to post_path(id: '03-travel') do %>
      <h4 class="tr">Newer Post</h4>
      <i class="fa fa-arrow-right nav-arrow" aria-hidden="true"></i>
    <% end %>

  </div>
</div>

app/views/posts/03-travel.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="banner welcome-post-banner" id = "" style="background-image: url(<%= image_path('https://res.cloudinary.com/ahg1/image/upload/c_crop,h_2000,w_4023/v1539105783/IMG_6340_mffmrc.jpg')%>);">
    </div>
  <div class="banner-comment mr-15"><p>(Photo: Panajachel, Guatemala - May 2018)</p></div>
</div>

<div class="container post-container">
  <div class="row">
    <div class="banner-heading">
      <h1>What I've Got</h1>
    </div>

    <p>
      Guatemala was the shiiiiiiit. It was the SHIT, guys.
    </p>
    <p>
      For 6 weeks I was in some random little town (Panajachel) with old ex-pats everywhere on the edge of the most beautiful lake ever (look, don't touch. It's really polluted). I lived in this sick house with an entire freaking secret garden and a little stream running through it. A gardener named Juan took care of all of it and his dog Paloma was a delightful little weirdo. I spent my weekends hiking volcanoes and exploring the very different towns around the lake.
    </p>

    <div class="container-fluid no-padding-container-fluid">
      <div class="row photo-row">
        <%= image_tag 'https://res.cloudinary.com/ahg1/image/upload/w_1332,h_1375/v1539877755/IMG_6332_mmvm75.jpg', class: "standard-photo", 'data-toggle':"tooltip", title:"pana"%>
        <%= image_tag 'https://res.cloudinary.com/ahg1/image/upload/w_1332,h_1375/v1539878763/IMG_6945_icfmqo.jpg', class: "standard-photo"%>
      </div>
      <div class="row photo-row">
        <%= image_tag 'https://res.cloudinary.com/ahg1/image/upload/w_1332,h_1375/v1539105842/IMG_6417_f6kkhv.jpg', class: "standard-photo"%>

        <%= image_tag 'https://res.cloudinary.com/ahg1/image/upload/w_1332,h_1375/v1539877609/IMG_6495_tl6z07.jpg', class: "standard-photo"%>
      </div>
    </div>


    <p><strong>
      Guatemala Highlights:
      </strong>
    </p>
    <ul>
      <li><p>Eating marshmallows roasted on a volcano</p></li>
      <li><p>Mayan traditions: the religion, clothes and languages still thrive</p></li>
      <li><p>Antigua is still a charming little city</p></li>
      <li><p>Blue sky, blue water, blue mountains</p></li>

    </ul>
    <p><strong>
      Guatemala Lows:</strong>
    </p>
    <p>
      <ul>
        <li><p>Food was meh (Nope, Mexican and Guatemalan food aren't the same - I missed the spice)</p></li>
        <li><p>The dogs were cool, but also bummed me out because there were a lot of mangy street dogs</p></li>
        <li><p>Trash. Everywhere.</p></li>
        <li><p>Extreme poverty and everything that comes with that like alcoholism, malnutrition and my own guilt of living in a nice house with clean water</p></li>
      </ul>



    <p>
      It was such an adventure place with scorpions popping up everywhere, always being mildly sick, having to walk 45 minutes to the nearest grocery store, taking boats -the only way to get across the lake - and being 98% positive we would all sink and die every single time. It. Was. Great.
    </p>
    <p>
      It also wore me the fuck out, ya know? Since Guatemala I've been trying to lay low a little and live in cities so I don't have to work so hard at survival. You see friends, traveling gets a little harder each year. My back hurts all the time and any mattress that isn't MY mattress makes that worse. I've got a bum knee, which is fun to say, but not fun to live. I miss LaCroix for some stupid reason. It's harder. You get set in your ways as you age and travel doesn't allow that. (Please calm down people who are older than me, I'm not saying I'm old, I'm just saying I'm not twenty anymore).
    </p>
    <p>
      That's also why I'm doing this, though. It's been cool to evaluate which luxuries I really don't want to live without (pickles, good sunscreen, lime squeezer) and what I was wasting money and space on before I picked up this mobile lifestyle (everything else that I purchased on Amazon. All of it.) It's also a challenge to not be a big ol' waste producer when traveling. I have to carry a reusable shopping bag, coffee mug and water bottle just to reduce some of my trash production (I know that sounds like not very much to those of you with an entire house, but that's like 1/8th of my luggage space). I had the same pair of jeans for a year, one pair of shorts for 6 months, one sweater, one Mexico shirt, one USA shirt, three neutral shirts and gym clothes.
    </p>
    <p>
      My point is: everything I have is calculated, valued and used until it dies and I like that, but I miss frivolousness.
    </p>
    <p>
      I don't know where this train goes after December-ish. I want to go back to the adventures of Guatemala or something like it and see more of the world and build immunities to more illnesses, but I also just want to have a little spot that I can fill with bullshit like fancy soaps and carpets and just call it mine and stay there until I die. It might not sound like it, but both are equally appealing right now and I cannot tell you which direction I will choose.
    </p>
  </div>
</div>

<div class="container-fluid">
  <div class="row photo-row">
    <%= image_tag 'https://res.cloudinary.com/ahg1/image/upload/w_2332,h_1375/v1539878951/IMG_6554_uodhuz.jpg', class: "long-photo"%>
    <div><p>(Photo: San Pedro, Guatemala - May 2018)</p></div>
  </div>
</div>

<div class="container">
  <div class="row nav-links">

    <%= link_to post_path(id: '02-mexico') do %>
      <i class="fa fa-arrow-left nav-arrow" aria-hidden="true"></i>
      <h4>Older Post</h4>
    <% end %>

    <%= link_to blog_path do %>
      <i class="fa fa-home nav-arrow" aria-hidden="true"></i>
      <h4>Home</h4>
    <% end %>

    <%= link_to post_path(id: '04-tinfoil') do %>
      <h4 class="tr">Newer Post</h4>
      <i class="fa fa-arrow-right nav-arrow" aria-hidden="true"></i>
    <% end %>

  </div>
</div>

app/views/posts/04-tinfoil.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="banner welcome-post-banner" id = "cholula" style="background-image: url(<%= image_path('https://res.cloudinary.com/ahg1/image/upload/v1539882341/IMG_8143_ivq9xb.jpg')%>);">
    </div>
  <div class="banner-comment mr-15"><p>(Photo: Plazuela de Los Sapos, Puebla - Sept 2018)</p></div>
</div>

<div class="container post-container">
  <div class="row">
    <div class="banner-heading">
      <h1>Team Tinfoil</h1>
    </div>

    <p>
      Ok, I'm not trying to be an alarmist, but Facebook's evil grasp is so far reaching that it just might be the end of civilized society. At best.
    </p>
    <p>
    Here's why:
    </p>
    <p>
      First of all: algorithms that show you what users only what they want to see. A world where you only see people and "news" articles that Facebook has precisely calculated to be EXACTLY what you like. The end result, as we've seen, is pockets of crazy a-holes who have no clue that they aren't batshit crazy (flat. earthers.) and it's really freaking me out. It's a very 1984 dystopian world where we are kept blind. I was especially scared when I found people who are posting 15-20 fake articles <strong>A DAY</strong> and just getting themselves more and more worked up about shit that's not real (FLAT EARTHERS - <a href="https://en.wikipedia.org/wiki/Pizzagate_conspiracy_theory" target="_blank" rel="noopener">PIZZA GATE -</a> <a href="https://www.independent.co.uk/news/world/americas/dog-with-ham-on-its-face-tricks-people-on-facebook-into-praying-for-burns-recovery-a6791511.html" target="_blank" rel="noopener">THIS DOG WITH A MELTED FACE</a>)
    </p>
    <p>
      Secondly, let's talk about the appearance of happiness. I tryyyy to keep it real, but fall short and we all do and maybe that's fine.  Then there's Shannon Watts who had a picture perfect life according to social media: nice little house outside of Denver, two adorably beautify girls and another baby on the way. A husband she called her "rock" and a seemingly lucrative business selling some weird wearable patches that did...patch things. You've probably heard the story; she and her children were devastatingly murdered at the hands of her husband and hearts were broken and no one could believe it. It received a lot of media attention, but to me it drove home the point that appearances on social media not only mean nothing, but might be harmful to people who feel afraid to express turmoil because they have to seem perfect. Add to that the research that increased social media use adds to anxiety and depression and there's no doubt in my mind that Facebook is an unhealthy vice at best.
    </p>
    <p>
      And for the nail in the coffin: let's talk about privacy -- Here's where I put on a foil hat so they can't hear my thoughts.
    </p>
    <p>
      Now as an American, the thought of privacy is kind of laughable. I have no doubts of the capabilities of the US government to monitor my every move. Instead of microwaving my passport to explode the chip inside, I've always just rolled with it. I assumed that I have nothing to hide and they are presumably catching the bad guys and spreading the obvious lie that the earth is round.  --Like a ball. I know, it's crazy -- Anyway, I didn't care. At all. In fact, I didn't try to hide anything because I figured there's no point in trying.
    </p>
    <p>
      But we're beyond that, my friends. I'll leave it at that and I'm going to go put on a foil corset so they can't read my guts as well as my thoughts. You can ask me my thoughts about this if you want to know more and I'll spill the beans.
    </p>
    <p>
      So, I deleted my Facebook. I can't decide if it's really annoying and lame to announce it and pretend you all should care, or if that's something that I do <em>have</em> to announce. It is so deeply engrained in our culture that couples dream about their social media announcement of an engagement perhaps more than the engagement itself.  If a baby's birth isn't announced on social media these days, was the baby actually even born? Do they have legal status? Doubt it. It's expected that major life events will be shared through social media, so turning my back on that feels a little treasonous.
    </p>
    <p>
      I have enjoyed sharing my travels on Facebook and seeing what other people are doing.  The hardest part of leaving is that on social media and in writing I come across as fairly charismatic and interesting, but in real life I want to go home and eat Twizzlers and watch something stupid on Netflix and I don't know how to answer the question "What's new?" or how much eye contact we humans make. I forgot. It shows.
    </p>
    <p>
      I have a dream of social media that's designed to be the exact opposite of Facebook in every way. Instead of having a thousand friends you barely know, we'll share updates with our inner circle. Instead of sharing short, attention grabbing posts: we share thoughtful and meaningful exchanges. Instead of triggering addiction in the brain, it triggers comfort. Instead of being a book of <em>faces</em>; it's a book of messy, honest lives and we don't fucking sell it to advertisers. Also free tinfoil hats for everyone.
    </p>
    <p>
      My next post will be about what has been called my "coding enterprise"- drop me a message if you have thoughts about this post or if you have questions about my code-ventures so I can either answer or avoid them.
    </p>
  </div>
</div>

<div class="container-fluid">
  <div class="row photo-row">
    <%= image_tag 'https://res.cloudinary.com/ahg1/image/upload/v1539880636/IMG_E8362_goycwu.jpg', class: "long-photo"%>
    <div><p>(Photo: Obviously Cholula, Puebla - Sept 2018)</p></div>
  </div>
</div>

<div class="container">
  <div class="row nav-links">

    <%= link_to post_path(id: '03-travel') do %>
      <i class="fa fa-arrow-left nav-arrow" aria-hidden="true"></i>
      <h4>Older Post</h4>
    <% end %>

    <%= link_to blog_path do %>
      <i class="fa fa-home nav-arrow" aria-hidden="true"></i>
      <h4>Home</h4>
    <% end %>

    <%= link_to post_path(id: '05-the-dead') do %>
      <h4>Newer Post</h4>
      <i class="fa fa-arrow-right nav-arrow" aria-hidden="true"></i>
    <% end %>

  </div>
</div>